version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq-network

  rabbitmq-ui:
    image: kbudde/rabbitmq-exporter:latest
    container_name: rabbitmq-exporter
    depends_on:
      - rabbitmq
    ports:
      - "9090:9090"
    environment:
      RABBIT_URL: http://rabbitmq:15672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
    networks:
      - rabbitmq-network

volumes:
  rabbitmq_data:

networks:
  rabbitmq-network:
    driver: bridge 