import { Task, User, TaskStatus, ID } from "../core/models";

// PHASE 3: Utility Types
// LEARNING GOAL: Mastering the built-in type transformers.

// 1. Partial<T>: Makes all properties optional.
// Great for "Update" operations where you only send changed fields.
export type TaskUpdatePayload = Partial<Task>;

// 2. Pick<T, K>: Selects only specific keys.
// Great for Lists/Previews where you don't need the full object.
export type TaskPreview = Pick<Task, "id" | "title" | "status" | "priority">;

// 3. Omit<T, K>: Removes specific keys.
// Useful for creating "CreateDTOs" where ID might be generated by backend.
export type CreateTaskDTO = Omit<Task, "id" | "createdAt" | "updatedAt">;

// 4. Readonly<T>: Makes object immutable.
// Essential for Functional Programming patterns or Redux-like state.
export type ImmutableTask = Readonly<Task>;

// 5. Record<K, T>: Creates a map type.
// Instead of index signatures {[key: string]: string}, use Record.
export type TaskDict = Record<ID, Task>;

// 6. Template Literal Types (Advanced)
// Can generate string types based on other types.
type AccessLevel = "read" | "write";
type Domain = "task" | "user";

// Generates: "read:task" | "read:user" | "write:task" | "write:user"
export type Permission = `${AccessLevel}:${Domain}`;
